### ISSUE TITLE
Point/getByTagTypeVersion does always return null

### ISSUE THREAD

**Issue by steppicrew** [rl3/Sponge-JS#2]
I always get an empty result calling

```
Point/getByTagTypeVersion/all/climate/1?left=-37.576171875&top=60.01617378693812&right=58.576171875&bottom=39.902401174361636
```

or

```
Point/getByTagTypeVersion/all/climate/2?left=-37.576171875&top=60.01617378693812&right=58.576171875&bottom=39.902401174361636
```

I think there should be a readable climate station in sight...

Additionally it would by nice to supply multiple versions as third parameter (preferred separated by '-')

```
Point/getByTagTypeVersion/all/climate/1-2?left=-37.576171875&top=60.01617378693812&right=58.576171875&bottom=39.902401174361636
```

**Comment by uhucrew** [comment]
Multiple versions are now supported.

The empty result I cannot reproduce. This link for instance delivers a 3.8MB kml-file:

https://agrohyd-api-dev.runlevel3.de/Point/getByTagTypeVersion/all/climate/1-2?left=-37.576171875&top=60.01617378693812&right=58.576171875&bottom=39.902401174361636&limit=10000

Is the session not included in the api call?
