### ISSUE TITLE
get random distributed results from Point/getByTagTypeVersion

### ISSUE THREAD

**Issue by steppicrew** [rl3/Sponge-JS#3]
requesting dataObjects for multiple versions in an fairly large area mostly returns only results with one version, because of limits in number of returned results.

For a user it's hard to tell, if there are results in a specific (apparently empty) area, until zoomed into that area.

**Comment by uhucrew** [comment]
random combined with limit is not possible in mongo queries
workaround created:
- bounding box is divided to x rows and y columns
- result of separate queries for all sub-boundingboxes is merged
