### ISSUE TITLE
"stack size exceeded" error if cbt.call very often called

### ISSUE THREAD

**Issue by uhucrew** [rl3/Sponge-JS#4]
To reproduce the error, the result maps have to be deleted first:

db.Polygon.remove({"mapname": "de_states_provinces_solution"})
db.Polygon.remove({"mapname": "de_states_provinces_solution__clipTmp"})

After that start runClipMapLists.js:

preprocessing/runClipMapLists.js
Wed May 21 2014 21:16:29 GMT+0200 (CEST) INFO:   database opened!
Wed May 21 2014 21:16:29 GMT+0200 (CEST) INFO:   database authenticated!
Wed May 21 2014 21:16:29 GMT+0200 (CEST) DEBUG:  PolygonApi: removeAllByMapname: de_states_provinces_solution : numRemoved: 0
Wed May 21 2014 21:16:29 GMT+0200 (CEST) DEBUG:  GeoTools: clipMaps: removedClippedMap: 0
Wed May 21 2014 21:16:29 GMT+0200 (CEST) DEBUG:  GeoTools: clipMaps: "ctIntersection" requested, calling "clipMapsIntersection" 9b018d5c380cd2f090b765ea053fc2b5 + harmonized_world_soil_database_121 -> de_states_provinces_solution
Wed May 21 2014 21:16:29 GMT+0200 (CEST) DEBUG:  PolygonApi: getCountByMapname: 9b018d5c380cd2f090b765ea053fc2b5 : 402
Wed May 21 2014 21:16:30 GMT+0200 (CEST) DEBUG:  PolygonApi: getCountByMapname: harmonized_world_soil_database_121 : 312175
Wed May 21 2014 21:16:47 GMT+0200 (CEST) DEBUG:  GeoTools: clipMapsIntersection: mapSubject finished, waiting for pending operations.
Wed May 21 2014 21:16:51 GMT+0200 (CEST) DEBUG:  GeoTools: clipMapsIntersection: mapClip finished, waiting for pending operations.
Wed May 21 2014 21:16:51 GMT+0200 (CEST) INFO:   GeoTools: clipMapsIntersection: ERROR mapClip processing incomplete: 303220 polygons not processed!
Wed May 21 2014 21:16:55 GMT+0200 (CEST) DEBUG:  GeoTools: clipMapsIntersection: mapClip finished, waiting for pending operations.
Wed May 21 2014 21:16:55 GMT+0200 (CEST) INFO:   GeoTools: clipMapsIntersection: ERROR mapClip processing incomplete: 303220 polygons not processed!

/var/node/Sponge-JS.dev/geoTools.js:1269
                                solution= clipper.clip(polySubjectClipper, pol
                                                  ^
RangeError: Maximum call stack size exceeded

**Comment by steppicrew** [comment]
Fixed by setting maxStackDepth to 1000 by default
