### ISSUE TITLE
invalid property-names

### ISSUE THREAD

**Issue by steppicrew** [rl3/Sponge-JS#5]
API call Model/getArgs mixes modelApi's global args into result. Those global args contain property names like "globals.sendMail" etc.
Property names containing a dot are not valid to be stored in mongodb (which is used to cache ui's data)

Please change global args to be an casacded object ({globals: {sendMail: ...}}) or replace dot with another character before sending result!

**Comment by uhucrew** [comment]
Replaced dot with colon
