### ISSUE TITLE
Fetch ParameterSets respecting a required step width

### ISSUE THREAD

**Issue by steppicrew** [rl3/Sponge-JS#6]
# Problem

There is no possibility to make sure a requested value is valid for a given step width (i.e. fetching a climate set for a given date, if ParameterSets contain values hourly)
# Solution
- add an optional parameter to getSet() specifying the desired step width (i.e. '1 day')
- add information to Schema, how to cumulate data in ParameterSets (sum [for transipration], average [for meanTemp], minimum [for minTemp], maximim [for maxTemp] etc.)
- getSet() should iterate all ParameterSets from given start until start + step is reached and cumulate values as defined in Schema
## Problems to solve
- What to do if ParameterSet's step is larger than requestet step (return value/portion, considering the cumulation info in Schema)
- Should it be implemented for Model's getSet-function to (to keep API independent from object type)? If yes, how?

**Comment by uhucrew** [comment]
Implemented for one-dimensional iterators
